version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - bootapp


  appservice:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/Contact?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8085:8081

    networks:
      - bootapp
  networks:
    bootapp:
  